#!/bin/bash
# Supabase Integration Quick Start Script
# This script guides you through the setup process

echo ""
echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                                                                    ║"
echo "║     ✅ SUPABASE INTEGRATION READY FOR YOUR GITHUB REPO! ✅          ║"
echo "║                                                                    ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 YOUR SETUP CHECKLIST:"
echo ""
echo "   [ ] 1. Add Supabase credentials to .env"
echo "   [ ] 2. Test connection locally"
echo "   [ ] 3. Push to GitHub"
echo "   [ ] 4. Set GitHub Secrets"
echo "   [ ] 5. Run GitHub Actions workflow"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1️⃣  - Add Your Credentials"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Option A: Interactive Setup (Recommended)"
echo "  $ python setup_supabase_credentials.py"
echo ""
echo "Option B: Manual Setup"
echo "  $ cp .env.example .env"
echo "  $ nano .env  # or edit with your favorite editor"
echo ""
echo "Get your credentials from:"
echo "  Supabase Dashboard → Settings → API"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2️⃣  - Test Connection Locally"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  $ python test_supabase_query.py"
echo ""
echo "This will:"
echo "  ✓ Verify your credentials"
echo "  ✓ Connect to Supabase"
echo "  ✓ Query your tables"
echo "  ✓ Display the dummy row you added! 🎉"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3️⃣  - Push to GitHub"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  $ git add -A"
echo "  $ git commit -m 'Add Supabase integration'"
echo "  $ git push origin main"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4️⃣  - Set GitHub Secrets"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Go to:"
echo "  GitHub → Your Repo → Settings → Secrets and variables → Actions"
echo ""
echo "Add 3 secrets:"
echo "  1. SUPABASE_URL = https://xxx.supabase.co"
echo "  2. SUPABASE_KEY = your_anon_key"
echo "  3. SUPABASE_SERVICE_ROLE_KEY = your_service_role_key"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 5️⃣  - Run GitHub Actions Workflow"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Go to:"
echo "  GitHub → Your Repo → Actions tab"
echo ""
echo "Find workflow:"
echo "  'Test Supabase Query'"
echo ""
echo "Click:"
echo "  'Run workflow' → 'Run workflow'"
echo ""
echo "Watch it:"
echo "  Execute and print your data from Supabase! 🎉"
echo ""

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                          📊 WHAT'S NEXT                            ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
echo "After testing, integrate into your code:"
echo ""
echo "  1. Read: INTEGRATE_SUPABASE.md"
echo "  2. Update: main.py"
echo "  3. Deploy: Push and watch data sync! 🚀"
echo ""

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                      📚 DOCUMENTATION                              ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
echo "Quick Guides:"
echo "  • GET_STARTED.md - Start here (5 min)"
echo "  • TEST_VIA_GITHUB_ACTIONS.md - How to query from GitHub (5 min)"
echo "  • INTEGRATE_SUPABASE.md - Update main.py (10 min)"
echo ""
echo "Complete Guides:"
echo "  • SUPABASE_SETUP.md - Full setup (15 min)"
echo "  • SUPABASE_QUICK_REFERENCE.md - Commands & snippets"
echo "  • README_SUPABASE.md - Documentation index"
echo ""
echo "Test Scripts:"
echo "  • test_supabase_query.py - Query your data"
echo "  • setup_supabase_credentials.py - Interactive setup"
echo "  • supabase_setup_helper.py - Verify everything"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Ready to get started? Follow the 5 steps above! 🚀"
echo ""
